<a href="https://colab.research.google.com/github/hwarang97/Pytorch_introduction/blob/main/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# tensor : 배열/행렬(numpy.narray) + GPU등의 가속기에 사용가능한 자료구조

In [2]:
import torch
import numpy as np

In [3]:
# tensor 초기화 방법 1
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [4]:
# numpy--> tensor 바꾸기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
# tensor --> tensor
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor : \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float) # 기본 자료형 float를 안쓰고 torch.float를 쓰는 이유는 뭘까?
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7020, 0.8445],
        [0.3941, 0.7545]]) 



In [6]:
# tensor를 무작위값 또는 상수값으로 생성해보기
shape = (2,3)
rand_tensor = torch.rand(shape) # 무작위값으로 생성
ones_tensor = torch.ones(shape) # 1값으로만 생성
zeros_tensor = torch.zeros(shape) # 0값으로만 생성

print(f'Random Tensor :\n {rand_tensor} \n')
print(f'Ones Tensor :\n {ones_tensor} \n')
print(f'zeros Tensor :\n {zeros_tensor} \n')

Random Tensor :
 tensor([[0.6499, 0.5376, 0.6879],
        [0.8562, 0.3510, 0.6349]]) 

Ones Tensor :
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros Tensor :
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [7]:
# 텐서 속성 (shape, dtype, 어느장치에 저장되는지 등)
tensor = torch.rand(3,4)

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device of tensor : {tensor.device}') # cpu라고 뜨면 cpu에서 진행되는것
                                             # 가속기를 GPU로 바꾸었지만 여전히 CPU로 저장되고 있음

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device of tensor : cpu


In [9]:
# Tensor는 가속기에서 사용할 수 있는 자료구조

# Colab에서는 GPU를 따로 배정받아야한다
# GPU가 존재하면 텐서를 이동합니다 (기본적으로는 CPU에 배정됨)
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [11]:
print(f'Device of tensor : {tensor.device}') # 사용하는 명령어를 쳐야 GPU로 이동된다

Device of tensor : cuda:0


In [17]:
tensor = torch.ones(4,4)
print(f'First row : {tensor[0]}')
print(f'First column : {tensor[:,0]}')
print(f'Last column : {tensor[:,-1]}')
print(f'Device of tensor : {tensor.device}') # 다시 CPU로 돌아간걸 보면, 가속기를 사용할 tensor마다 GPU로 이동시켜야하는듯
tensor[:,1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
Device of tensor : cpu
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # 기존 텐서를 이용해서 새로운 텐서 붙여서 만들기
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [26]:
#@title
# 텐서곱(행렬곱)
# y1, y2, y3는 모두 같은 값을 가짐

y1 = tensor @ tensor.T           
y2 = tensor.matmul(tensor.T) # 텐서 하나에서 연산 (matnul = matrix multiplizing)
y3 = torch.rand_like(y1) # torch에서 텐서 연산
torch.matmul(tensor, tensor.T, out=y3)

print(f'y1 : \n {y1} \n')
print(f'y2 : \n {y2} \n')
print(f'y3 : \n {y3} \n')

# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 가짐
z1 = tensor * tensor # 이거는 전치를 안하네
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f'z1 : \n {z1} \n')
print(f'z2 : \n {z2} \n')
print(f'z3 : \n {z3} \n')

y1 : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y2 : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3 : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

z1 : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z2 : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z3 : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [28]:
# in_place 연산(요소별 연산정도로 해석)
print(f'{tensor}\n')
tensor.add_(5)# 요소별로 5만큼 더하기
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [31]:
# Numpy bridge (공유 정도로 새거하면 될듯)
# CPU상의 텐서와 Numpy 배열은 메모리 공간을 공유하기때문에, 하나를 변경하면 다른 하나도 변경된다
# 주의할것은 Numpy는 CPU에서만 쓰이므로 CPU내에서만 공유가 성립

t = torch.ones(5)
print(f't: {t}\n')
n = t.numpy()
print(f'n : {n}')

t: tensor([1., 1., 1., 1., 1.])

n : [1. 1. 1. 1. 1.]


In [32]:
# CPU내에서는 메모리가 공유되므로, 변경사항도 공유
t.add_(1)
print(f't: {t}\n')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])

n: [2. 2. 2. 2. 2.]


In [33]:
# Numpy 배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
